gauges:
- title: raspi-k8s-master CPU
  position: [[0, 0], [40, 6]]
  rate-ms: 30000
  color: 10
  percent-only: true
  cur:
    sample: cat /tmp/kube-node | grep raspi-k8s-master | awk '{print $3}' | tr -d "%"
  max:
    sample: echo 100
  min:
    sample: echo 0
- title: raspi-k8s-worker01 CPU
  position: [[0, 6], [40, 6]]
  rate-ms: 30000
  color: 13
  percent-only: true
  cur:
    sample: cat /tmp/kube-node | grep raspi-k8s-worker01 | awk '{print $3}' | tr -d "%"
  max:
    sample: echo 100
  min:
    sample: echo 0
- title: raspi-k8s-worker02 CPU
  position: [[0, 12], [40, 6]]
  rate-ms: 30000
  color: 14
  percent-only: true
  cur:
    sample: cat /tmp/kube-node | grep raspi-k8s-worker02 | awk '{print $3}' | tr -d "%"
  max:
    sample: echo 100
  min:
    sample: echo 0
- title: raspi-k8s-master Mem
  position: [[40, 0], [40, 6]]
  rate-ms: 30000
  color: 10
  cur:
    sample: cat /tmp/kube-node | grep raspi-k8s-master | awk '{print $4}' | tr -d "Mi"
  max:
    sample: echo 4096
  min:
    sample: echo 0
- title: raspi-k8s-worker01 Mem
  position: [[40, 6], [40, 6]]
  rate-ms: 30000
  color: 13
  cur:
    sample: cat /tmp/kube-node | grep raspi-k8s-worker01 | awk '{print $4}' | tr -d "Mi"
  max:
    sample: echo 4096
  min:
    sample: echo 0
- title: raspi-k8s-worker02 Mem
  position: [[40, 12], [40, 6]]
  rate-ms: 30000
  color: 14
  cur:
    sample: cat /tmp/kube-node | grep raspi-k8s-worker02 | awk '{print $4}' | tr -d "Mi"
  max:
    sample: echo 4096
  min:
    sample: echo 0
textboxes:
- title: Status
  position: [[0, 18], [80, 23]]
  rate-ms: 30000
  sample: >-
    kubectl top node > /tmp/kube-node;
    kubectl get all --all-namespaces > /tmp/kube-all;
    echo "Pod:$(cat /tmp/kube-all | grep pod/ | grep 'Running' | wc -l)"
    "Service:$(cat /tmp/kube-all | grep service/ | wc -l)"
    "Daemonset:$(cat /tmp/kube-all | grep daemonset.apps/ | wc -l)"
    "Statefulset:$(cat /tmp/kube-all | grep daemonset.apps/ | wc -l)"
    "Deployment:$(cat /tmp/kube-all | grep deployment.apps/ | wc -l)"
    "Replicaset:$(cat /tmp/kube-all | grep replicaset.apps/ | wc -l)";
    echo "";
    echo "Service";
    kubectl get svc -A | grep -v ClusterIP | awk '{print $1, $2, $3, $6}' | column -t;
