gauges:
- title: raspi-k8s-master CPU
  position: [[0, 0], [40, 6]]
  rate-ms: 5000
  color: 10
  percent-only: true
  cur:
    sample: kubectl top node --no-headers --use-protocol-buffers raspi-k8s-master | awk '{print $3}' | tr -d "%" | grep -E "[0-9]+" || echo -1
  max:
    sample: echo 100
  min:
    sample: echo 0
- title: raspi-k8s-worker01 CPU
  position: [[0, 6], [40, 6]]
  rate-ms: 5000
  color: 13
  percent-only: true
  cur:
    sample: kubectl top node --no-headers --use-protocol-buffers raspi-k8s-worker01 | awk '{print $3}' | tr -d "%" | grep -E "[0-9]+" || echo -1
  max:
    sample: echo 100
  min:
    sample: echo 0
  triggers:
  - title: raspi-k8s-worker02 is Down
    condition: 
- title: raspi-k8s-worker02 CPU
  position: [[0, 12], [40, 6]]
  rate-ms: 5000
  color: 14
  percent-only: true
  cur:
    sample: kubectl top node --no-headers --use-protocol-buffers raspi-k8s-worker02 | awk '{print $3}' | tr -d "%" | grep -E "[0-9]+" || echo -1
  max:
    sample: echo 100
  min:
    sample: echo 0
- title: raspi-k8s-master Mem
  position: [[40, 0], [40, 6]]
  rate-ms: 5000
  color: 10
  cur:
    sample: kubectl top node --no-headers --use-protocol-buffers raspi-k8s-master | awk '{print $4}' | tr -d "Mi" | grep -E "[0-9]+" || echo -1
  max:
    sample: echo 4096
  min:
    sample: echo 0
- title: raspi-k8s-worker01 Mem
  position: [[40, 6], [40, 6]]
  rate-ms: 5000
  color: 13
  cur:
    sample: kubectl top node --no-headers --use-protocol-buffers raspi-k8s-worker01 | awk '{print $4}' | tr -d "Mi" | grep -E "[0-9]+" || echo -1
  max:
    sample: echo 4096
  min:
    sample: echo 0
- title: raspi-k8s-worker02 Mem
  position: [[40, 12], [40, 6]]
  rate-ms: 5000
  color: 14
  cur:
    sample: kubectl top node --no-headers --use-protocol-buffers raspi-k8s-worker02 | awk '{print $4}' | tr -d "Mi" | grep -E "[0-9]+" || echo -1
  max:
    sample: echo 4096
  min:
    sample: echo 0
textboxes:
- title: Status
  position: [[0, 18], [80, 22]]
  rate-ms: 4000
  sample: >-
    kubectl get all --all-namespaces > /tmp/kube-all;
    echo "pod:$(cat /tmp/kube-all | grep pod/ | grep 'Running' | wc -l)"
    "rs:$(cat /tmp/kube-all | grep replicaset.apps/ | wc -l)"
    "deploy:$(cat /tmp/kube-all | grep deployment.apps/ | wc -l)"
    "ds:$(cat /tmp/kube-all | grep daemonset.apps/ | wc -l)"
    "sts:$(cat /tmp/kube-all | grep daemonset.apps/ | wc -l)"
    "svc:$(cat /tmp/kube-all | grep service/ | wc -l)";
    echo "";
    echo "NodePort Services:";
    kubectl get svc -A --no-headers | grep -v ClusterIP | awk '{print $2, $6}' | column -t;
