---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-html
  namespace: publish-app
data:
  index.html: |
    Welcome to Apache(httpd)!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: publish-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: httpd:alpine
        name: httpd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: contents
          mountPath: /usr/local/apache2/htdocs/httpd/
      volumes:
      - name: contents
        configMap:
          name: httpd-html
