apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-path
  namespace: publish-app
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        backend:
          service: 
            name: nginx-clusterip
            port:
              number: 80
      - path: /httpd
        backend:
          service:
            name: httpd-clusterip
            port:
              number: 80
